# Generated by Django 5.1 on 2024-08-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayaate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
