# Generated by Django 5.1 on 2024-08-28 15:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayaate', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
